# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8fbb8464efea7fbbae8e82cc298abea9464b4618b6264ddc99aa5828141c0ea457951e7718da563c0dde8954ed9273213db05d440f7fbdb79f65b6d3e50429c
  email_secret_key: ca4b6be3b7355c789e9309303072c4aa752a4691e48cbd5b43a0b4f88f12b31b630cec1d016385e5f3cabdc76ef693932fa086fad4d6e7f01eb9c9a19b4bd224

test:
  secret_key_base: 784bb7c7f793229d4bd8470a7eb403d1c17adaed5b5f366c8bff06f76a751972f8866b41943ef99b9d210a6ee006bbf19d1091a7df8ee3f4f04249a0fff45414
  email_secret_key: 08645d6a071075326f5c8b3c9a5fae266e0920664dc5c84fdc7b5e92cd714ac8647702f985f085a7a151274227074e182686b765bd81c4e12a4097bc73506e49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_secret_key: <%= ENV["EMAIL_SECRET_KEY"] %>
